"""
outputs/bdd_generator.py — BDD Gherkin Senaryo Üretim Modülü
Sorumlu: Halise İncir

Açıklama:
Analiz edilen fonksiyonel gereksinimleri Gherkin formatında BDD test senaryolarına
dönüştürür. Her gereksinim için en az 1 happy path ve 1 negative senaryo üretilir.
Sonuçlar hem list[str] olarak döner hem de outputs/generated/scenarios.feature
dosyasına yazılır.

Çıktı formatı (list[str]):
    [
        "Feature: Kullanıcı Girişi\\n\\nScenario: ...\\n  Given ...\\n  When ...\\n  Then ...\\n",
        ...
    ]

Notlar:
- Sadece req_type == \"FUNCTIONAL\" olan gereksinimler işlenir.
- LLM çağrısı başarısız olursa ilgili gereksinim için fallback Gherkin metni döner;
  pipeline çökmez (graceful degradation).
- .feature dosyası header'ı: # Generated by AutoReq | {timestamp}
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from loguru import logger

from core.models import AnalysisReport, Requirement
from modules.llm_client import LLMClient, LLMClientError
from modules.llm_response_utils import extract_json_object
from modules.bdd_prompts import (
    build_bdd_generation_system_prompt,
    build_bdd_generation_user_prompt,
)

_log = logger.bind(module="bdd_generator")

# Varsayılan çıktı dizini
_GENERATED_DIR = Path(__file__).parent / "generated"


# ---------------------------------------------------------------------------
# Yardımcı Fonksiyonlar
# ---------------------------------------------------------------------------


def _steps_to_gherkin_lines(keyword: str, steps: list) -> str:
    """Adım listesini Gherkin satırlarına dönüştürür.

    Args:
        keyword: Gherkin anahtar kelimesi (Given / When / Then).
        steps: Adım metinleri listesi.

    Returns:
        str: Her adım için '  Given/When/Then <adım>\\n' formatında metin.
    """
    if not steps:
        return f"  {keyword} (adım belirtilmedi)\n"
    lines = ""
    for i, step in enumerate(steps):
        kw = keyword if i == 0 else "And"
        lines += f"  {kw} {step}\n"
    return lines


def _build_gherkin_block(feature_title: str, scenario: dict, req_id: str) -> str:
    """Bir senaryo sözlüğünden geçerli Gherkin metin bloğu oluşturur.

    Args:
        feature_title: Feature başlığı.
        scenario: 'scenario_title', 'given', 'when', 'then' anahtarlarını içeren dict.
        req_id: Gereksinim ID'si (Feature yorumuna eklenir).

    Returns:
        str: Tam Gherkin senaryo bloğu.
    """
    title = scenario.get("scenario_title") or "Senaryo"
    given_steps = scenario.get("given") or []
    when_steps = scenario.get("when") or []
    then_steps = scenario.get("then") or []

    block = f"Feature: {feature_title}  # {req_id}\n\n"
    block += f"  Scenario: {title}\n"
    block += _steps_to_gherkin_lines("Given", given_steps)
    block += _steps_to_gherkin_lines("When", when_steps)
    block += _steps_to_gherkin_lines("Then", then_steps)
    return block


def _make_fallback_gherkin(req: Requirement) -> List[str]:
    """LLM çağrısı başarısız olduğunda kullanılan temel Gherkin metinleri.

    Args:
        req: Dönüştürülemeyen Requirement nesnesi.

    Returns:
        list[str]: Happy path ve negative senaryo için 2 Gherkin metin bloğu.
    """
    feature = f"Gereksinim: {req.text[:50].strip()}"
    happy = (
        f"Feature: {feature}  # {req.id}\n\n"
        f"  Scenario: Başarılı akış (fallback)\n"
        f"  Given Sistem hazır durumda\n"
        f"  When Kullanıcı işlemi gerçekleştirir\n"
        f"  Then İşlem başarıyla tamamlanmalı\n"
    )
    negative = (
        f"Feature: {feature}  # {req.id}\n\n"
        f"  Scenario: Olumsuz akış (fallback)\n"
        f"  Given Sistem hazır durumda\n"
        f"  When Kullanıcı geçersiz veri girer\n"
        f"  Then Hata mesajı gösterilmeli\n"
    )
    return [happy, negative]


def _normalize_llm_payload(payload: dict, req_id: str) -> List[str]:
    """LLM'den dönen JSON payload'ı geçerli Gherkin bloklarına dönüştürür.

    Args:
        payload: LLM'den gelen ham JSON sözlük.
        req_id: Gereksinim ID'si.

    Returns:
        list[str]: [happy_path_gherkin, negative_scenario_gherkin]
    """
    feature_title = payload.get("feature_title") or f"Gereksinim {req_id}"
    results: List[str] = []

    happy = payload.get("happy_path")
    if isinstance(happy, dict):
        results.append(_build_gherkin_block(feature_title, happy, req_id))

    negative = payload.get("negative_scenario")
    if isinstance(negative, dict):
        results.append(_build_gherkin_block(feature_title, negative, req_id))

    # En az bir blok garantisi
    if not results:
        results = _make_fallback_gherkin(
            Requirement(
                id=req_id,
                text=feature_title,
                req_type="FUNCTIONAL",
            )
        )

    return results


# ---------------------------------------------------------------------------
# BDDGenerator Sınıfı
# ---------------------------------------------------------------------------


class BDDGenerator:
    """Fonksiyonel gereksinimlerden Gherkin formatında BDD senaryoları üretir.

    LLM (Gemini) kullanarak her FUNCTIONAL gereksinim için en az 1 happy path
    ve 1 negative senaryo içeren Gherkin metin blokları üretir.

    Args:
        llm_client: Dışarıdan enjekte edilebilir LLM istemcisi (test/DI için).
                    Verilmezse generate() çağrısında otomatik oluşturulur.
    """

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        self._llm_client = llm_client

    def _get_client(self) -> LLMClient:
        """Lazy-init: istemciyi ilk ihtiyaç anında oluşturur.

        Returns:
            LLMClient: Yapılandırılmış LLM istemcisi.

        Raises:
            LLMClientError: API key tanımlı değilse.
        """
        if self._llm_client is None:
            self._llm_client = LLMClient()
        return self._llm_client

    def _generate_single_bdd(self, req: Requirement) -> List[str]:
        """Tek bir gereksinim için LLM'e çağrı yapar ve Gherkin blokları döner.

        Args:
            req: BDD senaryosuna dönüştürülecek Requirement.

        Returns:
            list[str]: [happy_path_gherkin, negative_gherkin] blokları.

        Raises:
            LLMClientError: LLM çağrısı başarısız olursa.
        """
        system_prompt = build_bdd_generation_system_prompt()
        user_prompt = build_bdd_generation_user_prompt(req)

        client = self._get_client()

        try:
            response = client.chat(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                metadata={
                    "module": "bdd_generator",
                    "action": "generate_bdd_scenarios",
                    "req_id": req.id,
                },
            )
        except LLMClientError:
            _log.exception("LLM çağrısı başarısız (BDD üretimi) | req_id={}", req.id)
            raise

        try:
            payload = extract_json_object(response.content)
        except ValueError as exc:
            _log.error(
                "LLM çıktısı JSON olarak çözülemedi | req_id={} preview={}",
                req.id,
                response.content[:300] if response.content else "",
            )
            raise LLMClientError(f"BDD çıktısı işlenemedi: {exc}") from exc

        return _normalize_llm_payload(payload, req.id)

    def generate(self, report: AnalysisReport) -> List[str]:
        """AnalysisReport içindeki FUNCTIONAL gereksinimleri Gherkin BDD senaryolarına dönüştürür.

        Her gereksinim için LLM'e ayrı çağrı yapılır. LLM hatası durumunda
        o gereksinim için fallback Gherkin metni eklenir; pipeline çökmez.

        Args:
            report: NLP ve LLM analizleri tamamlanmış rapor nesnesi.

        Returns:
            list[str]: Her biri geçerli Gherkin formatında Feature/Scenario/Given/When/Then
                       bloklarından oluşan string listesi.
                       Her FUNCTIONAL gereksinim için minimum 1 happy + 1 negative senaryo.
        """
        functional_reqs = [
            req
            for req in report.parsed_doc.requirements
            if req.req_type == "FUNCTIONAL"
        ]

        if not functional_reqs:
            _log.info(
                "BDD üretimi atlandı: FUNCTIONAL gereksinim yok | toplam_gereksinim={}",
                len(report.parsed_doc.requirements),
            )
            return []

        _log.info(
            "BDD üretimi başlatıldı | functional_count={}",
            len(functional_reqs),
        )

        scenarios: List[str] = []

        for req in functional_reqs:
            try:
                blocks = self._generate_single_bdd(req)
                scenarios.extend(blocks)
                _log.debug("BDD senaryoları üretildi | req_id={} blocks={}", req.id, len(blocks))
            except (LLMClientError, ValueError) as exc:
                _log.warning(
                    "BDD senaryosu üretilemedi, fallback kullanılıyor | req_id={} hata={}",
                    req.id,
                    exc,
                )
                scenarios.extend(_make_fallback_gherkin(req))

        _log.info("BDD üretimi tamamlandı | toplam_blok={}", len(scenarios))
        return scenarios

    def write_feature_file(
        self,
        scenarios: List[str],
        output_path: Optional[Path] = None,
    ) -> Path:
        """Gherkin senaryolarını .feature dosyasına yazar.

        Dosya başına '# Generated by AutoReq | {timestamp}' header'ı eklenir.
        Senaryolar '\\n---\\n' ayırıcısıyla birleştirilir.

        Args:
            scenarios: generate() metodundan dönen Gherkin blok listesi.
            output_path: Yazılacak dosya yolu. None ise
                         outputs/generated/scenarios.feature kullanılır.

        Returns:
            Path: Yazılan .feature dosyasının mutlak yolu.
        """
        if output_path is None:
            _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
            output_path = _GENERATED_DIR / "scenarios.feature"
        else:
            output_path.parent.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = f"# Generated by AutoReq | {timestamp}\n\n"

        content = header + "\n# ---\n\n".join(scenarios)

        output_path.write_text(content, encoding="utf-8")
        _log.info("BDD .feature dosyası yazıldı | path={} scenarios={}", output_path, len(scenarios))
        return output_path
