"""
outputs/bdd_generator.py — BDD Gherkin Senaryo Üretim Modülü
Sorumlu: Halise İncir

Açıklama:
Analiz edilen fonksiyonel gereksinimleri Gherkin formatında BDD test senaryolarına
dönüştürür. Her gereksinim için en az 1 happy path ve 1 negative senaryo üretilir.
Sonuçlar hem list[str] olarak döner hem de outputs/generated/scenarios.feature
dosyasına yazılır.

Çıktı formatı (list[str]):
    [
        "Feature: Kullanıcı Girişi\\n\\nScenario: ...\\n  Given ...\\n  When ...\\n  Then ...\\n",
        ...
    ]

Notlar:
- Sadece req_type == \"FUNCTIONAL\" olan gereksinimler işlenir.
- LLM çağrısı başarısız olursa ilgili gereksinim için fallback Gherkin metni döner;
  pipeline çökmez (graceful degradation).
- .feature dosyası header'ı: # Generated by AutoReq | {timestamp}
"""

from __future__ import annotations

import concurrent.futures
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from loguru import logger

from core.models import AnalysisReport, Requirement
from modules.llm_client import LLMClient, LLMClientError
from modules.llm_response_utils import extract_json_object
from modules.bdd_prompts import (
    build_bdd_generation_system_prompt,
    build_bdd_generation_user_prompt,
    build_bdd_generation_batch_system_prompt,
    build_bdd_generation_batch_user_prompt,
)

_log = logger.bind(module="bdd_generator")

# Varsayılan çıktı dizini
_GENERATED_DIR = Path(__file__).parent / "generated"


# ---------------------------------------------------------------------------
# Yardımcı Fonksiyonlar
# ---------------------------------------------------------------------------


def _steps_to_gherkin_lines(keyword: str, steps: list) -> str:
    """Adım listesini Gherkin satırlarına dönüştürür.

    Args:
        keyword: Gherkin anahtar kelimesi (Given / When / Then).
        steps: Adım metinleri listesi.

    Returns:
        str: Her adım için '  Given/When/Then <adım>\\n' formatında metin.
    """
    if not steps:
        return f"  {keyword} (adım belirtilmedi)\n"
    lines = ""
    for i, step in enumerate(steps):
        kw = keyword if i == 0 else "And"
        lines += f"  {kw} {step}\n"
    return lines


def _build_gherkin_block(feature_title: str, scenario: dict, req_id: str) -> str:
    """Bir senaryo sözlüğünden geçerli Gherkin metin bloğu oluşturur.

    Args:
        feature_title: Feature başlığı.
        scenario: 'scenario_title', 'given', 'when', 'then' anahtarlarını içeren dict.
        req_id: Gereksinim ID'si (Feature yorumuna eklenir).

    Returns:
        str: Tam Gherkin senaryo bloğu.
    """
    title = scenario.get("scenario_title") or "Senaryo"
    given_steps = scenario.get("given") or []
    when_steps = scenario.get("when") or []
    then_steps = scenario.get("then") or []

    block = f"Feature: {feature_title}  # {req_id}\n\n"
    block += f"  Scenario: {title}\n"
    block += _steps_to_gherkin_lines("Given", given_steps)
    block += _steps_to_gherkin_lines("When", when_steps)
    block += _steps_to_gherkin_lines("Then", then_steps)
    return block


def _make_fallback_gherkin(req: Requirement) -> List[str]:
    """LLM çağrısı başarısız olduğunda kullanılan temel Gherkin metinleri.

    Args:
        req: Dönüştürülemeyen Requirement nesnesi.

    Returns:
        list[str]: Happy path ve negative senaryo için 2 Gherkin metin bloğu.
    """
    feature = f"Gereksinim: {req.text[:50].strip()}"
    happy = (
        f"Feature: {feature}  # {req.id}\n\n"
        f"  Scenario: Başarılı akış (fallback)\n"
        f"  Given Sistem hazır durumda\n"
        f"  When Kullanıcı işlemi gerçekleştirir\n"
        f"  Then İşlem başarıyla tamamlanmalı\n"
    )
    negative = (
        f"Feature: {feature}  # {req.id}\n\n"
        f"  Scenario: Olumsuz akış (fallback)\n"
        f"  Given Sistem hazır durumda\n"
        f"  When Kullanıcı geçersiz veri girer\n"
        f"  Then Hata mesajı gösterilmeli\n"
    )
    return [happy, negative]


def _normalize_llm_payload(payload: dict, req_id: str) -> List[str]:
    """LLM'den dönen JSON payload'ı geçerli Gherkin bloklarına dönüştürür.

    Args:
        payload: LLM'den gelen ham JSON sözlük.
        req_id: Gereksinim ID'si.

    Returns:
        list[str]: [happy_path_gherkin, negative_scenario_gherkin]
    """
    feature_title = payload.get("feature_title") or f"Gereksinim {req_id}"
    results: List[str] = []

    happy = payload.get("happy_path")
    if isinstance(happy, dict):
        results.append(_build_gherkin_block(feature_title, happy, req_id))

    negative = payload.get("negative_scenario")
    if isinstance(negative, dict):
        results.append(_build_gherkin_block(feature_title, negative, req_id))

    # En az bir blok garantisi
    if not results:
        results = _make_fallback_gherkin(
            Requirement(
                id=req_id,
                text=feature_title,
                req_type="FUNCTIONAL",
            )
        )

    return results


# ---------------------------------------------------------------------------
# BDDGenerator Sınıfı
# ---------------------------------------------------------------------------


_BDD_CHUNK_SIZE = 10
_BDD_BATCH_MAX_TOKENS = 4096


def _chunk_list(lst: List, size: int) -> List[List]:
    return [lst[i:i + size] for i in range(0, len(lst), size)]


class BDDGenerator:
    """Fonksiyonel gereksinimlerden Gherkin formatında BDD senaryoları üretir.

    LLM (Gemini) kullanarak her FUNCTIONAL gereksinim için en az 1 happy path
    ve 1 negative senaryo içeren Gherkin metin blokları üretir.
    Gereksinimler chunk'lara bölünerek paralel LLM çağrılarıyla işlenir.

    Args:
        llm_client: Dışarıdan enjekte edilebilir LLM istemcisi (test/DI için).
                    Verilmezse generate() çağrısında otomatik oluşturulur.
    """

    def __init__(self, llm_client: Optional[LLMClient] = None) -> None:
        self._llm_client = llm_client

    def _get_client(self) -> LLMClient:
        if self._llm_client is None:
            # BDD üretimi yapısal bir işlem olduğundan f/p açısından en hızlı model olan Gemini 2.5 Flash tercih edildi
            self._llm_client = LLMClient(model_name="google/gemini-2.5-flash", max_output_tokens=_BDD_BATCH_MAX_TOKENS)
        return self._llm_client

    def _generate_single_bdd(self, req: Requirement) -> List[str]:
        """Tek bir gereksinim için LLM'e çağrı yapar ve Gherkin blokları döner.

        Args:
            req: BDD senaryosuna dönüştürülecek Requirement.

        Returns:
            list[str]: [happy_path_gherkin, negative_gherkin] blokları.

        Raises:
            LLMClientError: LLM çağrısı başarısız olursa.
        """
        system_prompt = build_bdd_generation_system_prompt()
        user_prompt = build_bdd_generation_user_prompt(req)

        client = self._get_client()

        try:
            response = client.chat(
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                metadata={
                    "module": "bdd_generator",
                    "action": "generate_bdd_scenarios",
                    "req_id": req.id,
                },
            )
        except LLMClientError:
            _log.exception("LLM çağrısı başarısız (BDD üretimi) | req_id={}", req.id)
            raise

        try:
            payload = extract_json_object(response.content)
        except ValueError as exc:
            _log.error(
                "LLM çıktısı JSON olarak çözülemedi | req_id={} preview={}",
                req.id,
                response.content[:300] if response.content else "",
            )
            raise LLMClientError(f"BDD çıktısı işlenemedi: {exc}") from exc

        return _normalize_llm_payload(payload, req.id)

    def _process_chunk(self, chunk: List[Requirement]) -> List[str]:
        """Tek bir chunk için LLM çağrısı yapar ve Gherkin blokları döner."""
        system_prompt = build_bdd_generation_batch_system_prompt()
        user_prompt = build_bdd_generation_batch_user_prompt(chunk)
        client = self._get_client()

        response = client.chat(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            metadata={"module": "bdd_generator", "action": "batch_generate_bdd"},
        )

        raw = extract_json_object(response.content)
        items = raw if isinstance(raw, list) else (list(raw.values())[0] if isinstance(raw, dict) and raw else [])

        req_index = {r.id: r for r in chunk}
        scenarios: List[str] = []
        returned_ids: set = set()

        for item in items:
            if not isinstance(item, dict):
                continue
            req_id = item.get("req_id", "")
            returned_ids.add(req_id)
            scenarios.extend(_normalize_llm_payload(item, req_id))

        for req in chunk:
            if req.id not in returned_ids:
                _log.warning("Chunk yanıtında req_id eksik, fallback | req_id={}", req.id)
                scenarios.extend(_make_fallback_gherkin(req_index[req.id]))

        return scenarios

    def _generate_batch_bdd(self, reqs: List[Requirement]) -> List[str]:
        """Gereksinimleri chunk'lara bölerek paralel LLM çağrılarıyla Gherkin bloklarına dönüştürür.

        Args:
            reqs: BDD senaryosuna dönüştürülecek Requirement listesi.

        Returns:
            list[str]: Gherkin formatında senaryo blokları (giriş sırasıyla).
        """
        chunks = _chunk_list(reqs, _BDD_CHUNK_SIZE)

        if len(chunks) == 1:
            return self._process_chunk(chunks[0])

        _log.info("BDD üretimi {} chunk'a bölündü, paralel işleniyor", len(chunks))
        with concurrent.futures.ThreadPoolExecutor(max_workers=len(chunks)) as executor:
            futures = [executor.submit(self._process_chunk, chunk) for chunk in chunks]
            results: List[str] = []
            for future in futures:
                try:
                    results.extend(future.result())
                except (LLMClientError, ValueError) as exc:
                    chunk_idx = futures.index(future)
                    _log.warning("BDD chunk {} başarısız, fallback | hata={}", chunk_idx, exc)
                    for req in chunks[chunk_idx]:
                        results.extend(_make_fallback_gherkin(req))
        return results

    def generate(self, report: AnalysisReport) -> List[str]:
        """AnalysisReport içindeki FUNCTIONAL gereksinimleri Gherkin BDD senaryolarına dönüştürür.

        Tüm gereksinimler tek bir toplu LLM çağrısıyla işlenir.
        LLM hatası durumunda tüm gereksinimler için fallback Gherkin metni döner.

        Args:
            report: NLP ve LLM analizleri tamamlanmış rapor nesnesi.

        Returns:
            list[str]: Her biri geçerli Gherkin formatında Feature/Scenario/Given/When/Then
                       bloklarından oluşan string listesi.
                       Her FUNCTIONAL gereksinim için minimum 1 happy + 1 negative senaryo.
        """
        functional_reqs = [
            req
            for req in report.parsed_doc.requirements
            if req.req_type == "FUNCTIONAL"
        ]

        if not functional_reqs:
            _log.info(
                "BDD üretimi atlandı: FUNCTIONAL gereksinim yok | toplam_gereksinim={}",
                len(report.parsed_doc.requirements),
            )
            return []

        _log.info(
            "BDD toplu üretimi başlatıldı | functional_count={}",
            len(functional_reqs),
        )

        try:
            scenarios = self._generate_batch_bdd(functional_reqs)
        except (LLMClientError, ValueError) as exc:
            _log.warning(
                "Toplu BDD üretimi başarısız, tüm req'ler için fallback | hata={}",
                exc,
            )
            scenarios = []
            for req in functional_reqs:
                scenarios.extend(_make_fallback_gherkin(req))

        _log.info("BDD üretimi tamamlandı | toplam_blok={}", len(scenarios))
        return scenarios

    def write_feature_file(
        self,
        scenarios: List[str],
        output_path: Optional[Path] = None,
        in_memory: bool = False,
    ) -> Path | io.BytesIO:
        """Gherkin senaryolarını .feature dosyasına yazar.

        Dosya başına '# Generated by AutoReq | {timestamp}' header'ı eklenir.
        Senaryolar '\\n---\\n' ayırıcısıyla birleştirilir.

        Args:
            scenarios: generate() metodundan dönen Gherkin blok listesi.
            output_path: Yazılacak dosya yolu. None ise
                         outputs/generated/scenarios.feature kullanılır.
            in_memory: True ise dosyayı disk yerine bellekte (io.BytesIO) üretir.

        Returns:
            Path | io.BytesIO: Yazılan .feature dosyasının mutlak yolu veya bellek tamponu.
        """
        import io

        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        header = f"# Generated by AutoReq | {timestamp}\n\n"
        content = header + "\n# ---\n\n".join(scenarios)

        if in_memory:
            buf = io.BytesIO(content.encode("utf-8"))
            buf.seek(0)
            _log.info("BDD .feature dosyası bellekte (BytesIO) oluşturuldu.")
            return buf

        if output_path is None:
            _GENERATED_DIR.mkdir(parents=True, exist_ok=True)
            output_path = _GENERATED_DIR / "scenarios.feature"
        else:
            output_path.parent.mkdir(parents=True, exist_ok=True)

        output_path.write_text(content, encoding="utf-8")
        _log.info("BDD .feature dosyası yazıldı | path={} scenarios={}", output_path, len(scenarios))
        return output_path
